name: Test, Credo

on: [push, release]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-elixir@v1
        with:
          version-file: ".tool-versions"
          version-type: "strict"
      - name: Install Dependencies
        run: |
          mix deps.get
      - name: Run Tests
        run: |
          mix do compile --warnings-as-errors, test
      - name: Run Credo
        run: |
          mix credo
      - name: Check Formatting
        run: |
          mix format --check-formatted
